# Generated by Django 2.2.24 on 2021-09-12 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('equipment_category', models.CharField(choices=[('Steam Power Gen', 'Steam Power Gen'), ('ORC', 'ORC')], default='Steam Power Gen', max_length=20)),
                ('customer_product', models.CharField(choices=[('Hotel', 'Hotel'), ('Supermarket', 'Supermarket'), ('Stainless steel', 'Stainless steel'), ('Alluminium', 'Alluminium')], default='Stainless steel', max_length=20)),
                ('install_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('specification_of_equipment', models.TextField()),
                ('customer', models.ForeignKey(limit_choices_to={'admin': False, 'supplier_flag': False}, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(limit_choices_to={'supplier_flag': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Supplier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
