# Generated by Django 2.2.24 on 2021-08-18 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('equipment_category', models.CharField(max_length=20)),
                ('customer', models.CharField(max_length=50)),
                ('customer_product', models.CharField(max_length=100)),
                ('install_date', models.DateField(default=django.utils.datetime_safe.date.today)),
                ('specification_of_equipment', models.TextField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
