# Generated by Django 2.2.24 on 2021-09-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='equipment_category',
            field=models.CharField(choices=[('Steam Power Gen', 'Steam Power Gen'), ('ORC', 'ORC')], default='Steam Power Gen', max_length=20),
        ),
        migrations.AlterField(
            model_name='reference',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier'),
        ),
    ]
