# Generated by Django 2.2.24 on 2021-07-27 11:30

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210720_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='install_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
