# Generated by Django 2.2.24 on 2021-09-12 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('supplier_flag', models.BooleanField(default=False)),
                ('heat_buyer_flag', models.BooleanField(default=False)),
                ('foundation_industry_flag', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('user_type', models.CharField(choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Heat Buyer', 'Heat Buyer'), ('Foundation Industry', 'Foundation Industry')], default='Heat Buyer', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FoundationIndustry',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level_one', models.CharField(choices=[('Metal', 'Metal'), ('Ceramics', 'Ceramics'), ('Chemicals', 'Chemicals'), ('Paper', 'Paper'), ('Cement', 'Cement'), ('Glass', 'Glass')], default='Metal', max_length=20)),
                ('level_two', models.CharField(choices=[('Stainless steel', 'Stainless steel'), ('Alluminium', 'Alluminium')], default='Stainless steel', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Foundation Industries',
            },
        ),
        migrations.CreateModel(
            name='HeatBuyer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level_one', models.CharField(choices=[('DHN', 'DHN'), ('Industry', 'Industry'), ('Commercial', 'Commercial'), ('Uni', 'Uni')], default='DHN', max_length=20)),
                ('level_two', models.CharField(choices=[('Hotel', 'Hotel'), ('Supermarket', 'Supermarket')], default='Hotel', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Heat Buyers',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('level_one', models.CharField(choices=[('Power Gen', 'Power Gen'), ('Heat Exchange', 'Heat Exchange'), ('TGS', 'TGS'), ('Heat Pumps', 'Heat Pumps')], default='Power Gen', max_length=20)),
                ('level_two', models.CharField(choices=[('Steam Power Gen', 'Steam Power Gen'), ('ORC', 'ORC')], default='Steam Power Gen', max_length=20)),
                ('website', models.URLField(default='None', max_length=100)),
            ],
        ),
    ]
