# Generated by Django 2.2.24 on 2021-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210902_1205'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favorited_by', to='app.Reference'),
        ),
        migrations.AlterField(
            model_name='foundationindustry',
            name='level_one',
            field=models.CharField(choices=[('Metal', 'Metal'), ('Ceramics', 'Ceramics'), ('Chemicals', 'Chemicals'), ('Paper', 'Paper'), ('Cement', 'Cement'), ('Glass', 'Glass')], default='Metal', max_length=20),
        ),
        migrations.AlterField(
            model_name='foundationindustry',
            name='level_two',
            field=models.CharField(choices=[('Stainless steel', 'Stainless steel'), ('Alluminium', 'Alluminium')], default='Stainless steel', max_length=20),
        ),
        migrations.AlterField(
            model_name='heatbuyer',
            name='level_one',
            field=models.CharField(choices=[('DHN', 'DHN'), ('Industry', 'Industry'), ('Commercial', 'Commercial'), ('Uni', 'Uni')], default='DHN', max_length=20),
        ),
        migrations.AlterField(
            model_name='heatbuyer',
            name='level_two',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Supermarket', 'Supermarket')], default='Hotel', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='level_one',
            field=models.CharField(choices=[('Power Gen', 'Power Gen'), ('Heat Exchange', 'Heat Exchange'), ('TGS', 'TGS'), ('Heat Pumps', 'Heat Pumps')], default='Power Gen', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='level_two',
            field=models.CharField(choices=[('Steam Power Gen', 'Steam Power Gen'), ('ORC', 'ORC')], default='Steam Power Gen', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Supplier', 'Supplier'), ('Heat Buyer', 'Heat Buyer'), ('Foundation Industry', 'Foundation Industry')], default='Heat Buyer', max_length=25),
        ),
    ]
